### ISSUE TITLE
AttributeError on the first execution.

### ISSUE THREAD

**Issue by pedrxd** [ptitbigorneau/BigBrotherBot-For-UrT43#1]
When doing the first execution, I get the next error:

`Using configuration file: b3.xml

Starting B3      : www.bigbrotherbot.net (b3) v1.10.11 [AngryBiscuit]
Autorestart mode : OFF
Checking update  : no update available
Traceback (most recent call last):
  File "/home/urt/b3/b3/run.py", line 224, in run_console
    b3.start(main_config, options)
  File "/home/urt/b3/b3/__init__.py", line 323, in start
    sys.stdout.write('Loading config   : %s\n' % getShortPath(mainconfig.fileName, True))
  File "/home/urt/b3/b3/__init__.py", line 257, in getShortPath
    confpath = getAbsolutePath('@conf/', decode) + os.path.sep
  File "/home/urt/b3/b3/__init__.py", line 179, in getAbsolutePath
    path = os.path.join(getConfPath(decode=False, conf=conf), path[6:])
  File "/home/urt/b3/b3/__init__.py", line 162, in getConfPath
    path = confdir or os.path.dirname(console.config.fileName)
AttributeError: 'NoneType' object has no attribute 'config'
press any key to continue...
`

Using python 2.7.9

**Comment by pedrxd** [comment]
I found a fast fix, that error is produced when you enter the config as relative path. So just write the full path to the config file and it wouldn't appear.
